version: "3.9"

services:
  db_app:
    image: postgres:16
    container_name: pg_app
    environment:
      POSTGRES_DB: ${BEEPER_REPPLACEMENT_DB}
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${BEEPER_REPLACEMENT_PG_PASS}
    ports:
      - "5434:5432"                  # app DB por el puerto 5432 del host
    command: ["postgres","-c","listen_addresses=*"]
    volumes:
      - pgdata_app:/var/lib/postgresql/data
      - ./db/beeper-replacement-init:/docker-entrypoint-initdb.d:ro   # scripts sólo 1ra vez
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d ${BEEPER_REPPLACEMENT_DB} || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5

  db_security:
    image: postgres:16
    container_name: pg_sec
    environment:
      POSTGRES_DB: ${SECURITY_DB}
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${SECURITY_PG_PASS}
    ports:
      - "5433:5432"                  # security DB por el puerto 5433 del host
    command: ["postgres","-c","listen_addresses=*"]
    volumes:
      - pgdata_sec:/var/lib/postgresql/data
      - ./db/security-init:/docker-entrypoint-initdb.d:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d ${SECURITY_DB} || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  pgdata_app:
  pgdata_sec: