version: "3.8"

services:
  async-messaging-db:
    image: postgres:15
    container_name: async-messaging-db
    environment:
      POSTGRES_USER: async_messaging
      POSTGRES_PASSWORD: async_messaging
      POSTGRES_DB: async_messaging_db
    ports:
      - "5435:5432"
    volumes:
      - async-messaging-pgdata:/var/lib/postgresql/data
      - ./db/migrations:/docker-entrypoint-initdb.d
    networks:
      - backend

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin
    networks:
      - backend

volumes:
  async-messaging-pgdata:

networks:
  backend:
    driver: bridge
